[package]
name = "backend"
version = "0.1.0"
edition = "2021"
build="build.rs"

[dependencies]
tch = "0.17.0"
anyhow = "1.0"
tiktoken-rs = "0.5.0"
tokio = { version = "1.0", features = ["full"] }
axum = "0.6"
serde = { version = "1.0", features = ["derive"] }