FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
COPY lead_finder ./lead_finder
COPY shared ./shared

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "-m", "lead_finder.main"]

